language: node_js
node_js:
  - node
script:
  - yarn build
  - echo "Commit sha - $TRAVIS_COMMIT"
  - mkdir -p dist/@swaym/root-config/$TRAVIS_COMMIT
  - mv dist/*.* dist/@swaym/root-config/$TRAVIS_COMMIT/
